<?php

$title = 'Admin';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('custom-collect', ['action' => 'import']) ?>">1. Import custom collects from shopify</a>
    <br>
    <a href="<?= $this->url('collect', ['action' => 'import']) ?>">2. Import collects from shopify</a>
    <br>
    <a href="<?= $this->url('product', ['action' => 'import']) ?>">3. Import products from shopify</a>
</p>
