<?php

$title = 'Custom collects';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>id</th>
        <th>title</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($custom_collects as $custom_collect) : ?>
        <tr>
            <td>
                <?php echo $this->escapeHtml($custom_collect->id_custom_collection);?>
            </td>
            <td><?php echo $this->escapeHtml($custom_collect->title);?></td>
        </tr>
    <?php endforeach; ?>
</table>